import type { Metadata } from "next";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "@/app/components/ConvexClientProvider";
import { SyncUserWithClerk } from "@/app/components/SyncUserWithClerk";
import { ThemeProvider } from "@/app/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" style={{colorScheme:"dark"}}>
      <body>
        <ClerkProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
              <ConvexClientProvider>
                <SyncUserWithClerk />
                {children}
              </ConvexClientProvider>
            </ThemeProvider>
          </ClerkProvider>
        </body>
      </html>

  );
}
