import type { Metadata } from "next";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { ConvexClientProvider } from "@/app/components/ConvexClientProvider";
import { SyncUserWithClerk } from "@/app/components/SyncUserWithClerk";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  
      <html lang="en">
        <body>
          <ClerkProvider>
            <ConvexClientProvider>
              <SyncUserWithClerk />
              {children}
            </ConvexClientProvider>
          </ClerkProvider>
        </body>
      </html>

  );
}
